# Generated by Django 4.2.1 on 2023-05-08 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='affairs',
            name='done',
            field=models.BooleanField(default=False, verbose_name='Выполнено'),
            preserve_default=False,
        ),
    ]
