# Generated by Django 4.2.1 on 2023-05-08 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0002_affairs_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affairs',
            name='text',
            field=models.TextField(max_length=30, verbose_name='Дело'),
        ),
    ]
